"""fresh

Revision ID: 10b8f1cfb5df
Revises: 
Create Date: 2019-11-08 19:33:24.980758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b8f1cfb5df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero',
    sa.Column('hero_name', sa.String(), nullable=True),
    sa.Column('hid', sa.Integer(), nullable=False),
    sa.Column('tot_match', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('loss', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('hid')
    )
    op.create_table('logo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logo_email'), 'logo', ['email'], unique=True)
    op.create_index(op.f('ix_logo_id'), 'logo', ['id'], unique=False)
    op.create_index(op.f('ix_logo_password_hash'), 'logo', ['password_hash'], unique=False)
    op.create_index(op.f('ix_logo_username'), 'logo', ['username'], unique=False)
    op.create_table('match',
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('tot_kills', sa.Integer(), nullable=True),
    sa.Column('tot_assist', sa.Integer(), nullable=True),
    sa.Column('tot_death', sa.Integer(), nullable=True),
    sa.Column('tot_gold', sa.Integer(), nullable=True),
    sa.Column('tot_xp', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('winner', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('mid')
    )
    op.create_table('ana',
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['hero_id'], ['hero.hid'], ),
    sa.PrimaryKeyConstraint('hero_id')
    )
    op.create_table('player',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('no_match', sa.Integer(), nullable=True),
    sa.Column('avg_gpm', sa.Integer(), nullable=True),
    sa.Column('avg_xpm', sa.Integer(), nullable=True),
    sa.Column('no_wins', sa.Integer(), nullable=True),
    sa.Column('no_losses', sa.Integer(), nullable=True),
    sa.Column('avg_kda', sa.Float(), nullable=True),
    sa.Column('mmr', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['logo.id'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('player_hero',
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('Performance', sa.String(), nullable=True),
    sa.Column('heroname', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hero_id'], ['hero.hid'], ),
    sa.PrimaryKeyConstraint('hero_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_hero')
    op.drop_table('player')
    op.drop_table('ana')
    op.drop_table('match')
    op.drop_index(op.f('ix_logo_username'), table_name='logo')
    op.drop_index(op.f('ix_logo_password_hash'), table_name='logo')
    op.drop_index(op.f('ix_logo_id'), table_name='logo')
    op.drop_index(op.f('ix_logo_email'), table_name='logo')
    op.drop_table('logo')
    op.drop_table('hero')
    # ### end Alembic commands ###
