"""heroname_addition

Revision ID: 1506bb29de06
Revises: aeb5d2307d56
Create Date: 2019-11-15 20:29:29.901532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1506bb29de06'
down_revision = 'aeb5d2307d56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_match', sa.Column('heroname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_match', 'heroname')
    # ### end Alembic commands ###
