"""new commit

Revision ID: aeb5d2307d56
Revises: 10b8f1cfb5df
Create Date: 2019-11-15 19:23:52.162667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb5d2307d56'
down_revision = '10b8f1cfb5df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_match',
    sa.Column('matchid', sa.Integer(), nullable=False),
    sa.Column('playerid', sa.Integer(), nullable=False),
    sa.Column('kill_count', sa.Integer(), nullable=True),
    sa.Column('death_count', sa.Integer(), nullable=True),
    sa.Column('assist_count', sa.Integer(), nullable=True),
    sa.Column('kdaratio', sa.Integer(), nullable=True),
    sa.Column('playername', sa.String(), nullable=True),
    sa.Column('xpm', sa.Integer(), nullable=True),
    sa.Column('gpm', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['matchid'], ['match.mid'], ),
    sa.PrimaryKeyConstraint('matchid', 'playerid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_match')
    # ### end Alembic commands ###
